In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
bikedata=pd.read_csv("SeoulBikeData.csv", encoding= 'unicode_escape')

In [ ]:
bikedata.head()

,Date,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [ ]:
bikedata=bikedata.drop('Date',axis=1)

In [ ]:
bikedata.head()

,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [ ]:
bikedata.Seasons=pd.Categorical(bikedata.Seasons)
bikedata['season_code']=bikedata.Seasons.cat.codes
#changing seasons in string type to categorical 
bikedata=bikedata.drop('Seasons',axis=1)

In [ ]:
bikedata.Holiday=pd.Categorical(bikedata.Holiday)
bikedata['holiday_code']=bikedata.Holiday.cat.codes
#changing seasons in string type to categorical 
bikedata=bikedata.drop('Holiday',axis=1)

In [ ]:
bikedata['Functioning Day']=pd.Categorical(bikedata['Functioning Day'])
bikedata['functioning_day_code']=bikedata['Functioning Day'].cat.codes
#changing seasons in string type to categorical 
bikedata=bikedata.drop('Functioning Day',axis=1)

In [ ]:
# Checking for missing values

nullValues = pd.concat([bikedata.isnull().sum()],axis=1, keys=['Null Values'])
nullValues[nullValues.sum(axis=1) > 0 ]

Empty DataFrame
Columns: [Null Values]
Index: []

### our dataset has no null values

In [ ]:
# Is any entries are duplicate or not?
print('Total Duplicate Entries: ' , bikedata.duplicated().sum())
print('Percentage of Duplication: ' , (bikedata.duplicated().sum() / len(bikedata) * 100).round(2) , '%')

Total Duplicate Entries:  0
Percentage of Duplication:  0.0 %

### our data set has no duplicate values

In [ ]:
from sklearn.model_selection import train_test_split

bikedata

,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),season_code,holiday_code,functioning_day_code
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,3,1,1
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,3,1,1
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,3,1,1
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,3,1,1
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,1003,19,4.2,34,2.6,1894,-10.3,0.0,0.0,0.0,0,1,1
8756,764,20,3.4,37,2.3,2000,-9.9,0.0,0.0,0.0,0,1,1
8757,694,21,2.6,39,0.3,1968,-9.9,0.0,0.0,0.0,0,1,1
8758,712,22,2.1,41,1.0,1859,-9.8,0.0,0.0,0.0,0,1,1
8759,584,23,1.9,43,1.3,1909,-9.3,0.0,0.0,0.0,0,1,1

In [ ]:
x = bikedata.drop('Rented Bike Count',axis=1)
y = bikedata['Rented Bike Count']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15,random_state=0) #splitting 85% for training and 15% for testing

In [ ]:


from sklearn.ensemble import RandomForestRegressor 
#applying random forest classifier as predicting categorical values (language column)
#Gaussian Classifier
rfr=RandomForestRegressor(n_estimators=101, random_state=0)
rfr.fit(x_train,y_train)

RandomForestRegressor(n_estimators=101, random_state=0)

In [ ]:
x_test

,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),season_code,holiday_code,functioning_day_code
4059,3,10.7,73,1.3,2000,6.0,0.00,0.0,0.0,1,1,1
6914,2,21.7,78,1.0,2000,17.6,0.00,0.0,0.0,0,1,1
233,17,3.6,65,4.3,1061,-2.3,0.03,0.0,0.4,3,1,1
982,22,-9.7,51,2.8,2000,-17.9,0.00,0.0,0.0,3,1,1
5967,15,33.6,58,3.6,1448,24.1,1.98,0.0,0.0,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
3481,1,8.4,58,1.1,2000,0.6,0.00,0.0,0.0,1,1,1
4917,21,23.8,68,2.2,694,17.5,0.00,0.0,0.0,2,1,1
6804,12,26.7,40,1.4,2000,11.9,2.92,0.0,0.0,0,1,1
4932,12,28.9,40,2.3,809,13.9,3.15,0.0,0.0,2,1,1
3539,11,17.7,44,1.5,945,5.2,2.51,0.0,0.0,1,1,1

In [ ]:
y_pred=rfr.predict(x_test)

In [ ]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df.head() #observing few actual values and the predicted values

      Actual   Predicted
4059     320  237.792079
6914     580  489.524752
233      226  404.019802
982      165  208.495050
5967     646  701.980198

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

MAE 138.1463523064635
MSE 49803.61554930075
RMSE 223.16723672909686

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
print("R2score",r2_score(y_test,y_pred)) #(coefficient of determination) regression score function.

R2score 0.8841257982808604